package.json

Update node-zopfli to 2.0.0, see also <https://github.com/webpack/compression-webpack-plugin/issues/2#issuecomment-245852416>

Update node-zopfli version

---

package.json

- Adds `standard-version` contribs standard release lib.

chore: Add contrib release tooling

---

package.json

link direcly to the plugin docs on webpack.js.org

---

.travis.yml
appveyor.yml
package-lock.json
package.json

build(defaults): update to v1.6.0

---

src/index.js

I want to implement `cache` and for cache key we need use `this.options` (as in https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/src/index.js#L161)

refactor: use `options` property for options

---

src/index.js

fix: `text/include/exclude` option behaviour

---

src/index.js

As in https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/src/index.js#L159
Also rename `content` to `input` and `use` full output path to invalidate cache

fix(index): reduce memory usage (`cacheKey.hash`)

---

package-lock.json
package.json
src/index.js

- Increase performance
Reference: https://github.com/webpack/webpack/pull/6470

perf: use `neo-async` instead `async`

---

src/index.js

perf(index): switch to `md4` for content hashing

---

README.md

docs: multiple compressed versions of assets for different algorithm

---

README.md
package-lock.json

chore: update lock file

---

README.md

fixes #150
No, because we have information about breaking changes in CHANGELOG
No

docs: remove wrong information about versions

---

.github/workflows/nodejs.yml
package-lock.json
package.json

chore(deps): update

---

test/CompressionPlugin.test.js
test/__snapshots__/CompressionPlugin.test.js.snap.webpack4
test/__snapshots__/CompressionPlugin.test.js.snap.webpack5

Rephrase test description.
Nothing.
N/A

tests: rephrase description

---

README.md
src/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5

Improve options validation + docs
No
No

Refactor improve docs and options

---

src/index.js
test/CompressionPlugin.test.js
test/algorithm.test.js
test/cache-option.test.js
test/compressionOptions-option.test.js
test/deleteOriginalAssets.test.js
test/exclude-option.test.js
test/filename-option.test.js
test/helpers/getCacheDirectory.js
test/helpers/index.js
test/helpers/removeCache.js
test/include-option.test.js
test/minRatio-option.test.js
test/test-option.test.js
test/threshold-option.test.js
test/validate-options.test.js

Enable cache by default for webpack@4
Yes
BREAKING CHANGE: the cache is true by default for webpack@4
No

feat: enable cache by default for webpack@4

---

README.md
src/index.js
test/CompressionPlugin.test.js
test/__snapshots__/CompressionPlugin.test.js.snap.webpack4
test/__snapshots__/CompressionPlugin.test.js.snap.webpack5
test/__snapshots__/exclude-option.test.js.snap.webpack4
test/__snapshots__/exclude-option.test.js.snap.webpack5
test/__snapshots__/include-option.test.js.snap.webpack4
test/__snapshots__/include-option.test.js.snap.webpack5
test/__snapshots__/test-option.test.js.snap.webpack4
test/__snapshots__/test-option.test.js.snap.webpack5

BREAKING CHANGE: default value of the `filename` option is `'[path].gz'`
no need `query` in `filename` by default
Yes
No

fix: default value of the `filename` option is `'[path].gz'`

---

README.md
package-lock.json
package.json
src/index.js
test/__snapshots__/CompressionPlugin.test.js.snap.webpack5
test/__snapshots__/algorithm.test.js.snap.webpack5
test/__snapshots__/cache-option.test.js.snap.webpack5
test/__snapshots__/compressionOptions-option.test.js.snap.webpack5
test/__snapshots__/deleteOriginalAssets.test.js.snap.webpack5
test/__snapshots__/exclude-option.test.js.snap.webpack5
test/__snapshots__/filename-option.test.js.snap.webpack5
test/__snapshots__/include-option.test.js.snap.webpack5
test/__snapshots__/minRatio-option.test.js.snap.webpack5
test/__snapshots__/test-option.test.js.snap.webpack5
test/__snapshots__/threshold-option.test.js.snap.webpack4
test/__snapshots__/threshold-option.test.js.snap.webpack5
test/fixtures/empty.js
test/helpers/getCompiler.js
test/threshold-option.test.js

fixes #167
No
just improve docs

docs: improve the `threshold` documentation

---

test/CompressionPlugin.test.js
test/helpers/readAsset.js

Ensure we don't break `gzip`
No
No

test: check on `gzip`

---

README.md
package-lock.json
package.json
src/index.js
test/__snapshots__/algorithm.test.js.snap.webpack4
test/__snapshots__/algorithm.test.js.snap.webpack5

docs: resolve todo

---

src/index.js
test/__snapshots__/CompressionPlugin.test.js.snap.webpack5
test/__snapshots__/algorithm.test.js.snap.webpack5
test/__snapshots__/cache-option.test.js.snap.webpack4
test/__snapshots__/cache-option.test.js.snap.webpack5
test/__snapshots__/compressionOptions-option.test.js.snap.webpack5
test/__snapshots__/deleteOriginalAssets.test.js.snap.webpack5
test/__snapshots__/exclude-option.test.js.snap.webpack5
test/__snapshots__/filename-option.test.js.snap.webpack5
test/__snapshots__/include-option.test.js.snap.webpack5
test/__snapshots__/minRatio-option.test.js.snap.webpack5
test/__snapshots__/test-option.test.js.snap.webpack5
test/__snapshots__/threshold-option.test.js.snap.webpack5
test/cache-option.test.js

fix: do not crash when the `algorithm` option return non `Buffer`

---

src/Webpack4Cache.js
src/Webpack5Cache.js
src/index.js
test/cache-option.test.js

Refactor code

---

src/index.js
test/CompressionPlugin.test.js
test/__snapshots__/CompressionPlugin.test.js.snap.webpack4
test/__snapshots__/CompressionPlugin.test.js.snap.webpack5
test/__snapshots__/test-option.test.js.snap.webpack4
test/__snapshots__/test-option.test.js.snap.webpack5
test/test-option.test.js

improve coverage + small refactor
No
No

Test coverage

---

package-lock.json
package.json
src/index.js
test/__snapshots__/filename-option.test.js.snap.webpack4
test/__snapshots__/filename-option.test.js.snap.webpack5
test/filename-option.test.js

fix: respect directories in output

---

package-lock.json
package.json
src/index.js
test/CompressionPlugin.test.js
test/__snapshots__/CompressionPlugin.test.js.snap
test/__snapshots__/algorithm.test.js.snap
test/__snapshots__/compressionOptions-option.test.js.snap
test/__snapshots__/deleteOriginalAssets.test.js.snap
test/__snapshots__/exclude-option.test.js.snap
test/__snapshots__/filename-option.test.js.snap
test/__snapshots__/include-option.test.js.snap
test/__snapshots__/minRatio-option.test.js.snap
test/__snapshots__/test-option.test.js.snap
test/__snapshots__/threshold-option.test.js.snap
test/helpers/EmitNewAsset.js
test/helpers/getCompiler.js
test/helpers/index.js

Run compress against assets added later by plugins
No
No

Feat: run compress against assets added later by plugins

---

package-lock.json
package.json
src/index.js
test/CompressionPlugin.test.js
test/__snapshots__/CompressionPlugin.test.js.snap

fix: compatibility with old plugins

---

package-lock.json
package.json
src/options.json
test/__snapshots__/validate-options.test.js.snap

add links in the schema.
None
No

feat: output documentation links on errors

---

test/__snapshots__/CompressionPlugin.test.js.snap
test/__snapshots__/deleteOriginalAssets.test.js.snap

test: update

---

package-lock.json
package.json
test/__snapshots__/CompressionPlugin.test.js.snap
test/__snapshots__/algorithm.test.js.snap
test/__snapshots__/compressionOptions-option.test.js.snap
test/__snapshots__/deleteOriginalAssets.test.js.snap
test/__snapshots__/exclude-option.test.js.snap
test/__snapshots__/filename-option.test.js.snap
test/__snapshots__/include-option.test.js.snap
test/__snapshots__/minRatio-option.test.js.snap
test/__snapshots__/test-option.test.js.snap
test/__snapshots__/threshold-option.test.js.snap

update deps and snapshots
no
no

chore: update deps

---

README.md
package-lock.json
src/index.js
test/__snapshots__/CompressionPlugin.test.js.snap
test/__snapshots__/algorithm.test.js.snap
test/__snapshots__/compressionOptions-option.test.js.snap
test/__snapshots__/deleteOriginalAssets.test.js.snap
test/__snapshots__/exclude-option.test.js.snap
test/__snapshots__/filename-option.test.js.snap
test/__snapshots__/include-option.test.js.snap
test/__snapshots__/minRatio-option.test.js.snap
test/__snapshots__/test-option.test.js.snap
test/__snapshots__/threshold-option.test.js.snap
test/filename-option.test.js

migrate on webpack API, also now you can change names using webpack hooks on the plugin level, see `TemplatedPlugin`
Yse, if you use custom function for the `filename` option
also deps updated

Refactor migrate on new api

---

lint-staged.config.js

chore: extend lint-staged, use eslint cache

---

package.json

fix: added `types` to `package.json`

---

lint-staged.config.js

update lint-staged config 
NA
NA

chore: update lint-staged config

---

README.md

>**Note**
>
>This is new Note syntax 
>**Warning**
>
>This is new Warning syntax
update note in readme.md
No
No

docs: update note in readme.md

---

.cspell.json

update ignore files in .cspell.json
No
No

chore: update ignore files in .cspell.json

---

README.md

add GitHub discussion badge
No
No

chore: add GitHub discussion badge

---

lint-staged.config.js
package-lock.json
package.json
src/index.js
test/__snapshots__/CompressionPlugin.test.js.snap
test/__snapshots__/algorithm.test.js.snap
test/__snapshots__/compressionOptions-option.test.js.snap
test/__snapshots__/deleteOriginalAssets.test.js.snap
test/__snapshots__/exclude-option.test.js.snap
test/__snapshots__/filename-option.test.js.snap
test/__snapshots__/include-option.test.js.snap
test/__snapshots__/minRatio-option.test.js.snap
test/__snapshots__/test-option.test.js.snap
test/__snapshots__/threshold-option.test.js.snap
types/index.d.ts

refactor: fix types

---

.github/ISSUE_TEMPLATE/SUPPORT.md

remove Gitter from issue templates
No
No

docs: remove Gitter from issue templates

---

.github/workflows/nodejs.yml
src/index.js
types/index.d.ts

fixes https://github.com/webpack-contrib/compression-webpack-plugin/issues/378
No
No

fix: `test`/`include`/`exclude` types

---

README.md
src/index.js
src/options.json
test/CompressionPlugin.test.js
test/__snapshots__/CompressionPlugin.test.js.snap
test/__snapshots__/deleteOriginalAssets.test.js.snap
test/__snapshots__/validate-options.test.js.snap
test/deleteOriginalAssets.test.js
test/validate-options.test.js
types/index.d.ts

fixes https://github.com/webpack-contrib/compression-webpack-plugin/issues/368
No
No

feat: support the `deleteOriginalAssets` option as a function

---

package-lock.json
package.json
types/index.d.ts

update dependencies to latest version
No
No

chore: update dependencies to latest version

---

.github/ISSUE_TEMPLATE/BUG.md
.github/ISSUE_TEMPLATE/DOCS.md
.github/ISSUE_TEMPLATE/FEATURE.md
.github/ISSUE_TEMPLATE/MODIFICATION.md
.github/ISSUE_TEMPLATE/SUPPORT.md

improving typos in ISSUE_TEMPLATE files.
No
No

docs: improving typos in ISSUE_TEMPLATE files.

---

package-lock.json
package.json
test/__snapshots__/CompressionPlugin.test.js.snap
test/__snapshots__/algorithm.test.js.snap
test/__snapshots__/compressionOptions-option.test.js.snap
test/__snapshots__/deleteOriginalAssets.test.js.snap
test/__snapshots__/exclude-option.test.js.snap
test/__snapshots__/filename-option.test.js.snap
test/__snapshots__/include-option.test.js.snap
test/__snapshots__/minRatio-option.test.js.snap
test/__snapshots__/test-option.test.js.snap
test/__snapshots__/threshold-option.test.js.snap
types/index.d.ts

update jest from v29 to v30
No
No

chore: update jest from v29 to v30
