webpack-contrib/compression-webpack-plugin

index.js
This is my proposed solution to #8
It simply replaces
```
var newFile = this.asset.replace(/\{file\}/g, file);
```
with a more thorough parsing of the file (treating it as a url to handle the query)
```
var parse = url.parse(file);
var sub = {
file: file,
path: parse.pathname,
query: parse.query
};
var newFile = this.asset.replace(/\{(file|path|query)\}/g, function(p0,p1) {
return sub[p1];
});
```
=> Permit {path} and {query} in asset name

README.md, index.js, package.json
Proposed solution for #2.
`algorithm: "zopfli"` loads zopfli.gzip for compression, if `node-zopfli` dependency is present
=> Add zopfli option

README.md, index.js
=> Add option to delete the original assets

README.md, index.js
=> feat: add option to change the filename

README.md
This is useful for webpack.js.org where the only lead-in description of this plugin "Compression plugin for webpack" which doesn't say much. See [this page](https://webpack.js.org/plugins/compression-webpack-plugin/) in the docs.
=> docs(README): improve lead-in description

src/index.js
- Zopfli has been broken out to it's own repo.
Squash merge commit message body ...
```
BREAKING CHANGE: The optional dependency for Zopfli was causing issues in consumers CI / CD chains, this option has now been removed.
MIGRATION: Zopfli is now in it's own plugin the options have remained the same. For those using the Zopfli option in `compression-webpack-plugin` swap it out for `https://github.com/webpack-contrib/zopfli-webpack-plugin`
```
=> refactor: Drops optional Zopfli dependency

src/index.js
Given that compression is most likely one of the last steps on the pipeline
chain, it makes sense that this plugin uses the `emit` event which is the last
step to add/modify assets before they're written to disk.
This plays nicely with other plugins that create and delete files
on the fly AFTER they're compiled
(for example https://github.com/jtefera/merge-files-webpack, which is the
recommeded solution for this issue
webpack-contrib/extract-text-webpack-plugin#179)
- Fixes #30 
- Fixes #57 
- Fixes #62 
- Fixes #63
> edited by @michael-ciniawsky (Formatting)
=> refactor: use `emit` event instead of `this-compilation`

README.md, src/index.js
Add an `include` && `exclude` option for `assets`
- Fixes https://github.com/webpack-contrib/compression-webpack-plugin/issues/81
Also fix `eslint` problems and fix typo('`') in documentation
=> feat: add `include` and `exclude` options (`options.include|options.exclude`)

README.md
=> docs(README): fix typo in `options` table (`options.minRatio`)

README.md, package-lock.json, package.json, src/index.js
No test here, but tested locally, all works fine :smile:
=> feat: add `cache`option (`options.cache`)

src/index.js
We should avoid using `JSON.stringify` because `data` is buffer and after get from cache we return `{type: 'Buffer', data: [...]}` and this object don't have `length` (because it is now not `Buffer` it is just plain object with properties) - `minRation` doesn't work.
Other cached package also can contain error. I investigate this right now.
=> fix(index): don't use `JSON.stringify()` to serialize the  `cache` data (`options.cache`)

package.json
Fixing `async`'s version does not seem to be required.
=> chore(package): relax semver range of `async` dependency (`dependencies`)

src/index.js
Why? Because `.toString()` convert binary data to utf8 and it is broke gzip files
=> fix: `cache` behavior

src/index.js
- Fixes #94
I also ran into the above issue and confirmed that ModuleFilenameHelpers.matchObject does not get an options object with either include or exclude. They were not getting passed to the internal options object. I removed the regExp option because I'm assuming that it was mistakenly added, as there's no reference to one in the project documentation and it's the typename for the test/include/exclude options.
https://github.com/Stavrus/wpctest
=> fix(index): add missing `include` && `exclude` options (`this.options`)

test/__snapshots__/validation.test.js.snap, test/validation.test.js
=> test: validation `unknown` option

README.md
Update the "getting started" section with an example importing the Compression Plugin (which is used just below).  This import (require) statement is currently not found in the README.
Not a huge deal, but could save somebody ~5 seconds of having to add that in themselves.
=> docs(readme): update with import example

README.md
Signed-off-by: Andrew Welch <andrew@nystudio107.com>
fixes #118
=> Add “Using Brotli”

README.md, src/index.js, test/__snapshots__/filename-option.test.js.snap, test/filename-option.test.js
=> feat: add options for `dir`, `name` and `ext` in filename option (fix #117)

README.md, package-lock.json
https://github.com/webpack-contrib/compression-webpack-plugin/issues/130
=> Updated minRatio verbiage

src/index.js
fixes #172
No
Hard to tests :disappointed:
=> fix: memory leak

README.md, src/index.js, test/CompressionPlugin.test.js, test/__snapshots__/filename-option.test.js.snap.webpack4, test/__snapshots__/filename-option.test.js.snap.webpack5, test/cache-option.test.js, test/filename-option.test.js
BREAKING CHANGE: filename` is changed, you need to return path with placholders
to avoid problems with immutable files
Yes:
- `filename: Function` should return filename with placeholders to avoid problems with immutable files
- the `[dir]` placeholder was replaced on the `[path]` placeholder
- added `[fragment]` and `[base]` placeholders
- 
No
=> refactor: `filename` option

README.md
=> docs: extended options table with missed `deleteOriginalAssets` boolean flag

README.md, package-lock.json, package.json, src/index.js, src/options.json, test/__snapshots__/CompressionPlugin.test.js.snap.webpack5, test/__snapshots__/algorithm.test.js.snap.webpack5, test/__snapshots__/cache-option.test.js.snap.webpack5, test/__snapshots__/compressionOptions-option.test.js.snap.webpack4, test/__snapshots__/compressionOptions-option.test.js.snap.webpack5, test/__snapshots__/deleteOriginalAssets.test.js.snap.webpack4, test/__snapshots__/deleteOriginalAssets.test.js.snap.webpack5, test/__snapshots__/exclude-option.test.js.snap.webpack5, test/__snapshots__/filename-option.test.js.snap.webpack5, test/__snapshots__/include-option.test.js.snap.webpack5, test/__snapshots__/minRatio-option.test.js.snap.webpack5, test/__snapshots__/test-option.test.js.snap.webpack5, test/__snapshots__/threshold-option.test.js.snap.webpack5, test/__snapshots__/validate-options.test.js.snap.webpack4, test/__snapshots__/validate-options.test.js.snap.webpack5, test/deleteOriginalAssets.test.js
Fixes #215 . Added option to not delete sourcemap when deleting the originalAsset
none
none
=> feat: add option to keep source maps

src/index.js, types/index.d.ts
fix types for `algorithm`, `algorithm` should be defined if you provide custom options, because by default we are using `ZlibOptions` and they should be used only for `gzip`
No
No
=> fix: types

package.json, src/cjs.js, src/index.js, test/cjs.test.js, types/cjs.d.ts, types/index.d.ts
fixes #273, improve DX for types
Potentially yes, but we use babel and our code in commonjs format, so we should generate types in the same format
Now you can use:
```
import {Rule} from 'compression-webpack-plugin'
```
=> feat: remove cjs wrapper and generate types in commonjs format

src/index.js, test/helpers/readAsset.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
None
=> chore: replace deprecated String.prototype.substr()

src/index.js
The default filename is "[path][base].br" if the algorithm is brotli.
no
=> default filename for brotli

src/index.js
fixes https://github.com/webpack-contrib/compression-webpack-plugin/issues/364
No
Compatibility for Node.js@18 and allow to reuse `require("crypto").createHash` if webpack is lower then https://github.com/webpack/webpack/pull/17628
=> fix: compatibility with Node.js@18
